package webservice;

public enum EventType {
	ZONE_BYPASSED,
    ZONE_RESTORED,
    ALL_ZONES_RESTORED,
    DISARMED,
    DAY,
    NIGHT,
    AWAY,
    VACATION,
    DAY_INSTANT,
    NIGHT_DELAYED,
    ZONE_TRIPPED,
    ZONE_TROUBLE,
    REMOTE_PHONE_ACCESS,
    REMOTE_PHONE_LOCKOUT,
    ZONE_AUTO_BYPASSED,
    ZONE_TROUBLE_CLEARED,
    PC_ACCESS,
    ALARM_ACTIVATED,
    ALARM_RESET,
    SYSTEM_RESET,
    MESSAGE_LOGGED

}
